logger:
  log_level: INFO
  log_path: log
  use_logcli: true
  use_logfile: false
  use_simplelog: true

system:
  # 0: red, 1: blue, -1: unknown
  team_color: -1
  unknown_color_safe_mode: true
  # -1: no referee stage, 0/1/2 -> stage1/stage2/stage3
  stage_ref: -1

runtime:
  debug_fps: 60
  max_infer_running: 1
  debug_reload_interval_ms: 1000
  target_capture_fps_min: 90
  target_capture_fps_max: 120
  max_drop_rate: 0.05
  max_jitter_ms: 2.5
  max_e2e_latency_ms: 35.0
  perf_log_interval_ms: 1000
